# This workflow runs src/wakatime-api/index.js, which garbs the API and outputs build files. The workflow 
# then commits those changes to the master branch, which is then grabbed by the original `README.md`.

name: Wakatime API

on:
  schedule:
  - cron: "0 4 * * *"

# Only enable for testing, because GitHub doesn't have it :shrug:
#on:
#  push:
#    branches:
#    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd src/wakatime-api && node index.js && cd ../..
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'src/wakatime-api/build/'
        author_name: github-actions
        author_email: github-actions@github.com
        cwd: '.'
        force: false
        signoff: false
        message: 'Update wakatime charts from GitHub Actions'
        ref: 'master'
        remove: ""
