# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wakatime API

on:
  push:
    branches:
    - master

#on:
#  schedule:
#  - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd src/wakatime-api && node index.js && cd ../..
    - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        add: 'src/wakatime-api/build/'
        author_name: Bobbbay
        author_email: abatterysingle@gmail.com
        cwd: '.'
        force: false
        signoff: false
        message: 'Update wakatime charts from GitHub Actions'
        ref: 'master'
        remove: ""
      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
