# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wakatime API

on:
  schedule:
  - cron: "0 4 * * *"

# Only enable for testing, because GitHub doesn't have it :shrug:
#on:
#  push:
#    branches:
#    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd src/wakatime-api && node index.js && cd ../..
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'src/wakatime-api/build/'
        author_name: Bobbbay
        author_email: abatterysingle@gmail.com
        cwd: '.'
        force: false
        signoff: false
        message: 'Update wakatime charts from GitHub Actions'
        ref: 'master'
        remove: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
